name: 'Get & Cache dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  cachingInput:
    description: 'Dependencies need to be cached or not'
    required : false
    default: 'true'
outputs:
  cachingOutput:
    description: 'Whether the cache was used or not.'
    value: ${{steps.install.outputs.cache}}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.cachingInput== 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'|| inputs.cachingInput=='false'
      id: install
      run: 
        npm ci
        echo "cache='${{ steps.cache.outputs.cache-hit }}'" >> $GITHUB_OUTPUT
      shell: bash