name: 'Get & Cache dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  cachingInput:
    description: 'Dependencies need to be cached or not'
    required : false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'|| inputs.cachingInput=='false'
      run: npm ci
      shell: bash